### ISSUE TITLE
Back-End Checklist

### ISSUE THREAD

**Issue by WizArdZ3658** [WizArdZ3658/University-Backend#1]
- [x] Design schema for **College**.
- [x] Design schema for **Student**.
- [x] Generate mock fake data, 100 colleges with 100 students in each college.
- [x] Use MongoDB (MongoDB-Atlas).
- [x] Get **College** details. **[API]**
- [x] Get **Student** details using college ID. **[API]**

**Comment by WizArdZ3658** [comment]
Back-end implemented and deployed.
