### ISSUE TITLE
Front-End Checklist

### ISSUE THREAD

**Issue by WizArdZ3658** [WizArdZ3658/University-Backend#2]
- [x] Show dashboards/charts by State.
- [x] Show dashboards/charts by Courses.
- [x] Should be able to drill down a particular sector and see the list.
Say I drill down to a particular college, College 1. You should show the following info.
- [x] It should show college details
- [x] Show list of students in that college
- [x] Show a list of similar colleges
- [x] Say I drill down to a particular student and then show student details.

**Comment by WizArdZ3658** [comment]
Front-end implemented and deployed.
